# Generated by Django 4.1.3 on 2022-11-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxi",
            fields=[
                (
                    "numImm",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("marque", models.CharField(max_length=20)),
                ("nb_place", models.IntegerField()),
                ("numMoteur", models.CharField(max_length=20)),
                ("poids_total", models.IntegerField()),
                ("poids_vide", models.IntegerField()),
                ("charge_utile", models.IntegerField()),
                ("carrosserie", models.CharField(max_length=10)),
            ],
        ),
    ]
