# Generated by Django 4.1.3 on 2022-11-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0002_taxi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carte_grise",
            fields=[
                ("numSerie", models.IntegerField(primary_key=True, serialize=False)),
                ("date_fabrication", models.DateField()),
            ],
        ),
    ]
