# Generated by Django 4.1.3 on 2022-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0003_carte_grise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visite",
            fields=[
                ("numVis", models.IntegerField(primary_key=True, serialize=False)),
                ("date_vis", models.DateField()),
                ("fin_vis", models.DateField()),
            ],
        ),
    ]
