# Generated by Django 4.1.3 on 2022-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0004_visite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assurance",
            fields=[
                ("ref", models.IntegerField(primary_key=True, serialize=False)),
                ("debut_ass", models.DateField()),
                ("fin_ass", models.DateField()),
            ],
        ),
    ]
