# Generated by Django 4.1.3 on 2022-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0005_assurance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "numAg",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nomAg", models.CharField(max_length=10)),
            ],
        ),
    ]
