# Generated by Django 4.1.3 on 2022-11-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0007_capacite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permi",
            fields=[
                (
                    "numPer",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
