# Generated by Django 4.1.3 on 2022-12-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0010_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
