# Generated by Django 4.1.3 on 2022-12-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0012_assurance_taxi_taxi_carte_grise"),
    ]

    operations = [
        migrations.AddField(
            model_name="assurance",
            name="agence",
            field=models.ForeignKey(
                blank=True,
                db_column="numAg",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.agence",
            ),
        ),
        migrations.AddField(
            model_name="capacite",
            name="permi",
            field=models.OneToOneField(
                blank=True,
                db_column="numPer",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.permi",
            ),
        ),
        migrations.AddField(
            model_name="chauffeur",
            name="capacite",
            field=models.OneToOneField(
                blank=True,
                db_column="numCap",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.capacite",
            ),
        ),
        migrations.AddField(
            model_name="chauffeur",
            name="permi",
            field=models.OneToOneField(
                blank=True,
                db_column="numPer",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.permi",
            ),
        ),
        migrations.AddField(
            model_name="taxi",
            name="chauffeur",
            field=models.OneToOneField(
                blank=True,
                db_column="numChf",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.chauffeur",
            ),
        ),
        migrations.AddField(
            model_name="visite",
            name="taxi",
            field=models.ForeignKey(
                blank=True,
                db_column="numImm",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.taxi",
            ),
        ),
    ]
