# Generated by Django 4.1.3 on 2022-12-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0013_assurance_agence_capacite_permi_chauffeur_capacite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxi",
            name="carte_grise",
        ),
        migrations.RemoveField(
            model_name="taxi",
            name="chauffeur",
        ),
    ]
