# Generated by Django 4.1.3 on 2022-12-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0014_remove_taxi_carte_grise_remove_taxi_chauffeur"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxi",
            name="carte_grise",
            field=models.OneToOneField(
                blank=True,
                db_column="numSerie",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.carte_grise",
            ),
        ),
        migrations.AddField(
            model_name="taxi",
            name="chauffeur",
            field=models.OneToOneField(
                blank=True,
                db_column="numChf",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.chauffeur",
            ),
        ),
    ]
