# Generated by Django 4.1.3 on 2022-12-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0015_taxi_carte_grise_taxi_chauffeur"),
    ]

    operations = [
        migrations.AddField(
            model_name="permi",
            name="Categorie",
            field=models.ManyToManyField(to="Uber.categorie"),
        ),
    ]
