# Generated by Django 4.1.3 on 2022-12-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0016_permi_categorie"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
    ]
