# Generated by Django 4.1.3 on 2022-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0017_delete_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart", models.CharField(max_length=30)),
                ("destination", models.CharField(max_length=30)),
                ("distance", models.IntegerField(default=1)),
            ],
        ),
    ]
