# Generated by Django 4.1.3 on 2022-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0018_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="montant",
            field=models.IntegerField(default=1),
        ),
    ]
