# Generated by Django 4.1.3 on 2022-12-21 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0021_course_taxi"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
