# Generated by Django 4.1.3 on 2022-12-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0023_course_desciption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="desciption",
            field=models.TextField(default="Description de la course"),
        ),
    ]
