# Generated by Django 4.1.3 on 2022-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0024_alter_course_desciption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="desciption",
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(default="Description de la course", max_length=255),
        ),
    ]
