# Generated by Django 4.1.3 on 2022-12-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0025_remove_course_desciption_course_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="permi",
            old_name="Categorie",
            new_name="categorie",
        ),
    ]
