# Generated by Django 4.1.3 on 2022-12-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0026_rename_categorie_permi_categorie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="date",
            new_name="dateCrs",
        ),
    ]
