# Generated by Django 4.1.3 on 2023-01-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0027_rename_date_course_datecrs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="distance",
        ),
    ]
