# Generated by Django 4.1.3 on 2023-01-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0029_course_distance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permi",
            name="categorie",
        ),
        migrations.RemoveField(
            model_name="chauffeur",
            name="date_naissance",
        ),
        migrations.RemoveField(
            model_name="chauffeur",
            name="lieu_naissance",
        ),
        migrations.RemoveField(
            model_name="chauffeur",
            name="permi",
        ),
        migrations.RemoveField(
            model_name="chauffeur",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="taxi",
            name="carrosserie",
        ),
        migrations.RemoveField(
            model_name="taxi",
            name="charge_utile",
        ),
        migrations.RemoveField(
            model_name="taxi",
            name="chauffeur",
        ),
        migrations.RemoveField(
            model_name="taxi",
            name="numMoteur",
        ),
        migrations.RemoveField(
            model_name="taxi",
            name="poids_total",
        ),
        migrations.RemoveField(
            model_name="taxi",
            name="poids_vide",
        ),
        migrations.AddField(
            model_name="chauffeur",
            name="permis",
            field=models.CharField(default="permis", max_length=5),
        ),
        migrations.AlterField(
            model_name="chauffeur",
            name="capacite",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="taxi",
            name="carte_grise",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="taxi",
            name="nb_place",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Capacite",
        ),
        migrations.DeleteModel(
            name="Carte_grise",
        ),
        migrations.DeleteModel(
            name="Categorie",
        ),
        migrations.DeleteModel(
            name="Permi",
        ),
    ]
