# Generated by Django 4.1.3 on 2023-01-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0030_remove_permi_categorie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxi",
            name="chauffeur",
            field=models.ForeignKey(
                blank=True,
                db_column="numChf",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Uber.chauffeur",
            ),
        ),
    ]
