# Generated by Django 4.1.3 on 2023-01-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Uber", "0031_taxi_chauffeur"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
    ]
